In [12]:
import pandas as pd
import os 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
root_dir = r'/home/check/DATA/university/yr3, hk1/DS111 - phân tích dữ liệu/Do_an/DS111/'

In [14]:
df = pd.read_csv(root_dir + 'Data/Silver/Silver_1.csv')
print(df.columns)
df.head()

Index(['Country_Code', 'Year', 'Partner_Name', 'standard_name',
       'Export_USD_Thousand', 'Import_USD_Thousand',
       'AHS_Weighted_Average_Percent', 'MFN_Weighted_Average_Percent',
       'AHS_Duty_Free_Tariff_Lines_Share_Percent', 'has_RCA',
       'has_Country_Growth', 'cc_rank', 'pv_rank', 'rl_rank', 'va_rank',
       'Log_Export', 'Log_Import', 'Tariff_Gap'],
      dtype='object')

,Country_Code,Year,Partner_Name,standard_name,Export_USD_Thousand,Import_USD_Thousand,AHS_Weighted_Average_Percent,MFN_Weighted_Average_Percent,AHS_Duty_Free_Tariff_Lines_Share_Percent,has_RCA,has_Country_Growth,cc_rank,pv_rank,rl_rank,va_rank,Log_Export,Log_Import,Tariff_Gap
0,ABW,2004,Aruba,Aruba,2599745.71,2533418.39,3.31,5.69,56.76,1,1,85.2,80.6,80.8,73.1,14.770925,14.745080,2.38
1,ABW,2005,Aruba,Aruba,3141038.78,4062240.72,2.22,5.78,47.31,1,1,88.3,96.1,78.0,85.6,14.960064,15.217246,3.56
2,ABW,2006,Aruba,Aruba,3441552.23,4351496.78,2.76,6.11,39.90,1,1,88.3,96.1,72.7,80.3,15.051433,15.286031,3.35
3,ABW,2007,Aruba,Aruba,3009284.60,4697153.46,2.39,5.91,52.70,1,1,88.3,96.6,75.1,78.4,14.917213,15.362467,3.52
4,ABW,2008,Aruba,Aruba,2899879.76,5598160.71,2.78,7.56,47.17,1,1,87.4,96.2,76.4,79.3,14.880180,15.537949,4.78

In [15]:
df.drop(columns=['Partner_Name'], inplace=True)
df.rename(columns={'standard_name': 'Country_Name'}, inplace=True)

In [16]:
df.head()

,Country_Code,Year,Country_Name,Export_USD_Thousand,Import_USD_Thousand,AHS_Weighted_Average_Percent,MFN_Weighted_Average_Percent,AHS_Duty_Free_Tariff_Lines_Share_Percent,has_RCA,has_Country_Growth,cc_rank,pv_rank,rl_rank,va_rank,Log_Export,Log_Import,Tariff_Gap
0,ABW,2004,Aruba,2599745.71,2533418.39,3.31,5.69,56.76,1,1,85.2,80.6,80.8,73.1,14.770925,14.745080,2.38
1,ABW,2005,Aruba,3141038.78,4062240.72,2.22,5.78,47.31,1,1,88.3,96.1,78.0,85.6,14.960064,15.217246,3.56
2,ABW,2006,Aruba,3441552.23,4351496.78,2.76,6.11,39.90,1,1,88.3,96.1,72.7,80.3,15.051433,15.286031,3.35
3,ABW,2007,Aruba,3009284.60,4697153.46,2.39,5.91,52.70,1,1,88.3,96.6,75.1,78.4,14.917213,15.362467,3.52
4,ABW,2008,Aruba,2899879.76,5598160.71,2.78,7.56,47.17,1,1,87.4,96.2,76.4,79.3,14.880180,15.537949,4.78